### ISSUE TITLE
Please add dismiss curve like instagram (bouncy feel)

### ISSUE THREAD

**Issue by sooxt98** [Mayb3Nots/zoom_pinch_overlay#1]

**Comment by Shawn-sudo** [comment]
<img width="587" alt="Screen Shot 2022-03-13 at 12 48 30 AM" src="https://user-images.githubusercontent.com/60294318/158046919-60c271a4-9783-43d8-b42e-6d028c019afc.png">
If you change the code like this and then recompile it, you would be able to achieve it

**Comment by Shawn-sudo** [comment]
fix #7
